"use client";

import { usePublicApplication } from "./public-application-context";

export function PublicApplicationReceipt() {
  const { state, meta } = usePublicApplication();
  const receipt = state.receipt!;
  return <main className="min-h-screen bg-surface px-5 py-12 text-foreground sm:px-8"><section className="mx-auto max-w-[680px] rounded-modal border border-border bg-card px-5 py-10 text-center shadow-[var(--shadow-1)] sm:px-10"><span aria-hidden="true" className="mx-auto grid h-14 w-14 place-items-center rounded-full bg-pass-bg text-2xl font-bold text-pass">✓</span><p className="mt-6 text-sm font-semibold text-pass">목 접수 완료</p><h1 className="mt-2 text-2xl font-bold tracking-[-0.025em]">접수 완료 상태를 확인했어요.</h1><p className="mt-3 leading-7 text-muted-strong">화면 검증을 위한 목 접수입니다.<br /><strong>실제 서버나 공연사에는 전달되지 않았습니다.</strong></p><section className="mt-8 rounded-card border border-border bg-surface p-5 text-left"><p className="text-sm text-muted">목 접수번호</p><strong className="num mt-1 block text-xl tracking-[0.02em] text-foreground">{receipt.number}</strong><dl className="mt-5 grid gap-x-4 gap-y-3 text-sm sm:grid-cols-[80px_1fr]"><dt className="text-muted">공연</dt><dd className="font-medium">{meta.performanceTitle}</dd><dt className="text-muted">공고</dt><dd className="font-medium">{meta.postingTitle}</dd><dt className="text-muted">배역</dt><dd className="font-medium">{meta.roleName}</dd><dt className="text-muted">처리 시각</dt><dd className="num font-medium">{receipt.submittedAt}</dd></dl></section><section className="mt-5 rounded-control border border-brand-line bg-brand-soft px-4 py-4 text-left"><h2 className="text-sm font-bold text-brand">테스트 안내</h2><p className="mt-2 text-sm leading-6 text-brand">이 화면의 접수번호와 상태는 브라우저에서만 생성됩니다. 실제 접수 기능은 API 연동 이후 제공됩니다.</p></section><button type="button" onClick={meta.onBack} className="mt-8 min-h-12 w-full rounded-control bg-brand px-5 text-base font-semibold text-white hover:bg-brand-strong">공고로 돌아가기</button></section></main>;
}
