"use client";

import Image from "next/image";
import type { ApplicationFieldInput } from "@/features/auditions/creation-types";
import type { ApplicationFormStep } from "@/features/applications/application-form";
import { youtubeVideoId } from "@/features/applications/application-form-state";
import type { ApplicationPhoto, CareerDraft, SubmissionState } from "@/features/applications/application-form-state";
import { usePublicApplication } from "./public-application-context";

export function PublicApplicationReview() {
  const { state, actions, meta } = usePublicApplication();
  const submitting = state.submissionState === "SUBMITTING";
  const steps = ["BASIC", "INTRODUCTION", "MATERIALS", "CAREER", "CUSTOM"] as const;
  return <main className="min-h-screen bg-surface pb-12 text-foreground"><header className="glass-surface sticky top-0 z-20 border-x-0 border-t-0"><div className="mx-auto flex min-h-16 max-w-[880px] items-center px-5 md:px-8"><span className="text-sm font-semibold text-brand">지원서 검토</span></div></header><div className="mx-auto max-w-[880px] px-5 py-8 md:px-8 md:py-12"><p className="text-sm font-semibold text-brand">마지막 확인</p><h1 className="mt-2 text-2xl font-bold tracking-[-0.025em] md:text-[28px]">작성한 내용을 확인해 주세요.</h1><p className="mt-3 leading-6 text-muted-strong">영역별 내용을 확인한 뒤 지원서를 제출해 주세요.</p><ReviewIssues disabled={submitting} /><div className="mt-8 space-y-4"><ReviewSection title="지원 배역"><p className="rounded-control border border-brand-line bg-brand-soft px-3 py-2 text-sm font-semibold text-brand">{meta.roleName}</p></ReviewSection>{steps.map((section) => <StepReview key={section} section={section} disabled={submitting} />)}</div><Consent consent={state.consent} disabled={submitting} error={state.submissionError.includes("동의") ? state.submissionError : ""} onChange={actions.updateConsent} /><SubmissionArea submitting={submitting} consent={state.consent} state={state.submissionState} error={state.submissionError} onSubmit={actions.submit} /></div></main>;
}

function StepReview({ section, disabled }: { section: ApplicationFormStep["section"]; disabled: boolean }) {
  const { state, actions, meta } = usePublicApplication();
  const step = meta.steps.find((item) => item.section === section);
  if (!step) return null;
  if (section === "MATERIALS") return <ReviewSection title={step.title} disabled={disabled} onEdit={() => actions.editSection(section)}><MediaSummary photos={state.photos} videoUrl={state.videoUrl} /></ReviewSection>;
  if (section === "CAREER") return <ReviewSection title={step.title} disabled={disabled} onEdit={() => actions.editSection(section)}><CareerSummary noCareer={state.noCareer} careers={state.careers} /></ReviewSection>;
  return <ReviewSection title={step.title} disabled={disabled} onEdit={() => actions.editSection(section)}><ReviewFields fields={step.fields} values={state.values} /></ReviewSection>;
}

function ReviewIssues({ disabled }: { disabled: boolean }) {
  const { state, actions } = usePublicApplication();
  if (!state.reviewIssues.length) return null;
  return <section aria-labelledby="review-issues-title" className="mt-6 rounded-card border border-fail/30 bg-fail-bg p-4"><h2 id="review-issues-title" className="text-sm font-bold text-fail">제출 전에 확인할 항목이 {state.reviewIssues.length}개 있어요</h2><ul className="mt-3 space-y-2">{state.reviewIssues.map((issue) => <li key={issue.section}><button type="button" disabled={disabled} onClick={() => actions.editSection(issue.section)} className="flex min-h-11 w-full items-center gap-2 rounded-control px-2 text-left text-sm text-fail hover:bg-card focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-fail disabled:cursor-not-allowed"><span aria-hidden="true">!</span><span className="min-w-0 flex-1"><strong>{issue.title}</strong> · {issue.message}</span><span className="shrink-0 font-semibold">수정</span></button></li>)}</ul></section>;
}

function ReviewSection({ title, disabled = false, onEdit, children }: { title: string; disabled?: boolean; onEdit?: () => void; children: React.ReactNode }) { return <section className="overflow-hidden rounded-card border border-border bg-card"><div className="flex items-center border-b border-border-soft bg-surface px-4 py-3"><h2 className="text-sm font-bold">{title}</h2>{onEdit ? <button type="button" disabled={disabled} onClick={onEdit} className="ml-auto min-h-11 rounded-control px-3 text-sm font-semibold text-brand hover:bg-brand-soft focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand disabled:cursor-not-allowed disabled:text-muted disabled:hover:bg-transparent">수정</button> : null}</div><div className="p-4">{children}</div></section>; }

function ReviewFields({ fields, values }: { fields: readonly ApplicationFieldInput[]; values: Readonly<Record<string, string>> }) { return <dl className="grid gap-x-8 gap-y-4 text-sm md:grid-cols-2">{fields.filter((field) => field.enabled).map((field) => <div key={field.id} className="grid grid-cols-[84px_minmax(0,1fr)] gap-3"><dt className="text-muted">{field.label}</dt><dd className="line-clamp-3 break-words whitespace-pre-wrap font-medium">{reviewValue(field, values) || <span className="font-normal text-muted">미입력</span>}</dd></div>)}</dl>; }
function reviewValue(field: ApplicationFieldInput, values: Readonly<Record<string, string>>) { if (field.inputType === "COMPOSITE") return field.config.fields?.map((part) => `${values[`${field.id}.${part.key}`] || "-"}${part.unit ?? ""}`).join(" · "); return values[field.id]; }

function MediaSummary({ photos, videoUrl }: { photos: readonly ApplicationPhoto[]; videoUrl: string }) { const attached = photos.filter((photo) => photo.status !== "ERROR"); const failedCount = photos.length - attached.length; const videoId = youtubeVideoId(videoUrl); return <div>{attached.length ? <div className="flex gap-2 overflow-x-auto pb-1">{attached.map((photo, index) => <div key={photo.id} className="relative h-[88px] w-[66px] shrink-0 overflow-hidden rounded-md border border-border"><Image src={photo.url} alt={index === 0 ? "대표 프로필 사진" : photo.name} fill unoptimized sizes="66px" className="object-cover" />{index === 0 ? <span className="absolute bottom-0 left-0 right-0 bg-brand px-1 py-0.5 text-center text-[10px] font-semibold text-white">대표</span> : null}</div>)}</div> : <p className="text-sm text-muted">사진 미첨부</p>}{failedCount ? <p className="mt-3 text-sm text-fail">첨부에 실패한 사진 {failedCount}개가 있어요.</p> : null}<p className="mt-3 text-sm text-muted-strong">{videoId ? `연결한 영상 · youtu.be/${videoId}` : "영상 미첨부"}</p></div>; }
function CareerSummary({ noCareer, careers }: { noCareer: boolean; careers: readonly CareerDraft[] }) { if (noCareer) return <p className="text-sm text-muted">경력 없음 (신인)</p>; if (!careers.length) return <p className="text-sm text-muted">경력 미입력</p>; return <ul className="divide-y divide-border-soft">{careers.map((career) => <li key={career.id} className="grid grid-cols-[56px_minmax(0,1fr)_auto] gap-3 py-3 text-sm"><span className="num text-muted">{career.year}</span><span className="min-w-0 break-words font-medium">{career.title}</span><span className="text-muted">{career.part}</span></li>)}</ul>; }

function Consent({ consent, disabled, error, onChange }: { consent: boolean; disabled: boolean; error: string; onChange: (consent: boolean) => void }) { const helpId = "application-consent-help"; const errorId = "application-consent-error"; return <section className={`mt-7 border-y border-border py-5 ${disabled ? "opacity-70" : ""}`}><label htmlFor="application-consent" className={`flex items-start gap-3 ${disabled ? "cursor-not-allowed" : "cursor-pointer"}`}><input id="application-consent" type="checkbox" checked={consent} disabled={disabled} aria-invalid={Boolean(error) || undefined} aria-describedby={[helpId, error ? errorId : ""].filter(Boolean).join(" ")} onChange={(event) => onChange(event.target.checked)} className="mt-1 h-4 w-4 shrink-0 accent-brand" /><span><strong className="block text-sm"><span className="mr-1 text-fail">[필수]</span>개인정보 안내를 확인하고 제출에 동의합니다</strong><span id={helpId} className="mt-1 block text-sm leading-6 text-muted">제출하면 공연사가 지원 정보를 열람할 수 있습니다. 운영 전 수집 목적, 보관 기간, 파기 기준과 동의 문안은 별도 정책 확정이 필요합니다.</span></span></label>{error ? <p id={errorId} role="alert" className="mt-3 text-sm font-medium text-fail">{error}</p> : null}</section>; }

function SubmissionArea({ submitting, consent, state, error, onSubmit }: { submitting: boolean; consent: boolean; state: SubmissionState; error: string; onSubmit: (result: "SUCCESS" | "ERROR") => void }) { const showFailureControl = process.env.NODE_ENV === "development"; const label = submitting ? "제출 중…" : state === "ERROR" ? "다시 제출" : consent ? "지원서 제출" : "동의하고 제출"; return <section className="mt-6" aria-labelledby="submission-title"><h2 id="submission-title" className="sr-only">제출 상태</h2><p className="text-sm leading-6 text-muted">현재 데모의 제출 내용과 조회 코드는 이 브라우저에만 유지됩니다.</p>{submitting ? <p role="status" className="mt-3 rounded-control border border-brand-line bg-brand-soft px-4 py-3 text-sm font-medium text-brand">작성 내용을 확인하고 있어요. 잠시만 기다려 주세요.</p> : null}{error && !error.includes("동의") ? <p role="alert" className="mt-3 rounded-control border border-fail/20 bg-fail-bg px-4 py-3 text-sm font-medium leading-6 text-fail">{error} 입력값은 유지됩니다. 다시 제출해 주세요.</p> : null}<button type="button" disabled={submitting} onClick={() => onSubmit("SUCCESS")} className="mt-4 inline-flex min-h-12 w-full items-center justify-center rounded-control bg-brand px-5 text-base font-semibold text-white transition-colors hover:bg-brand-strong focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand disabled:cursor-wait disabled:bg-border disabled:text-muted">{label}</button>{showFailureControl ? <details className="mt-4 text-xs text-muted"><summary className="cursor-pointer px-2 py-1 font-medium hover:text-muted-strong">개발용 상태 확인</summary><button type="button" disabled={submitting} onClick={() => onSubmit("ERROR")} className="mt-2 min-h-11 rounded-control px-3 text-xs font-semibold text-muted hover:bg-fail-bg hover:text-fail focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand">실패 흐름 보기</button></details> : null}</section>; }
