"use client";

import Image from "next/image";
import type { ApplicationFieldInput } from "@/features/auditions/creation-types";
import { youtubeVideoId } from "@/features/applications/application-form-state";
import type { ApplicationPhoto, CareerDraft, SubmissionState } from "@/features/applications/application-form-state";
import { usePublicApplication } from "./public-application-context";

export function PublicApplicationReview() {
  const { state, actions, meta } = usePublicApplication();
  const disabled = state.submissionState === "SUBMITTING";
  return <main className="min-h-screen bg-surface pb-12 text-foreground"><header className="glass-surface sticky top-0 z-20 border-x-0 border-t-0"><div className="mx-auto flex min-h-16 max-w-[880px] items-center px-5 sm:px-8"><span className="text-sm font-semibold text-brand">지원서 검토</span></div></header><div className="mx-auto max-w-[880px] px-5 py-8 sm:px-8 sm:py-12"><p className="text-sm font-semibold text-brand">마지막 확인</p><h1 className="mt-2 text-2xl font-bold tracking-[-0.025em]">지원서를 제출하기 전에 확인해 주세요.</h1><p className="mt-2 text-muted-strong">제출 후에는 수정할 수 없어요.</p><div className="mt-8 space-y-4"><ReviewSection title="지원 배역"><p className="rounded-control border border-brand-line bg-brand-soft px-3 py-2 text-sm font-semibold text-brand">{meta.roleName}</p></ReviewSection>{hasEnabled(meta.fields, "BASIC") ? <ReviewSection title="기본 정보" disabled={disabled} onEdit={() => actions.editSection("BASIC")}><ReviewFields fields={meta.fields.filter((field) => field.section === "BASIC")} values={state.values} /></ReviewSection> : null}{hasEnabled(meta.fields, "MATERIALS") ? <ReviewSection title="사진과 영상" disabled={disabled} onEdit={() => actions.editSection("MATERIALS")}><MediaSummary photos={state.photos} videoUrl={state.videoUrl} /></ReviewSection> : null}{hasEnabled(meta.fields, "CAREER") ? <ReviewSection title="경력" disabled={disabled} onEdit={() => actions.editSection("CAREER")}><CareerSummary noCareer={state.noCareer} careers={state.careers} /></ReviewSection> : null}{hasEnabled(meta.fields, "CUSTOM") ? <ReviewSection title="추가 질문" disabled={disabled} onEdit={() => actions.editSection("CUSTOM")}><ReviewFields fields={meta.fields.filter((field) => field.section === "CUSTOM")} values={state.values} /></ReviewSection> : null}</div><Consent consent={state.consent} disabled={disabled} onChange={actions.updateConsent} /><SubmissionArea disabled={disabled} consent={state.consent} state={state.submissionState} error={state.submissionError} onSubmit={actions.submit} /></div></main>;
}

function hasEnabled(fields: readonly ApplicationFieldInput[], section: ApplicationFieldInput["section"]) { return fields.some((field) => field.section === section && field.enabled); }

function ReviewSection({ title, disabled = false, onEdit, children }: { title: string; disabled?: boolean; onEdit?: () => void; children: React.ReactNode }) { return <section className="overflow-hidden rounded-card border border-border bg-card"><div className="flex items-center border-b border-border-soft bg-surface px-4 py-3"><h2 className="text-sm font-bold">{title}</h2>{onEdit ? <button type="button" disabled={disabled} onClick={onEdit} className="ml-auto min-h-9 rounded-control px-3 text-sm font-semibold text-brand hover:bg-brand-soft disabled:cursor-not-allowed disabled:text-muted disabled:hover:bg-transparent">수정</button> : null}</div><div className="p-4">{children}</div></section>; }

function ReviewFields({ fields, values }: { fields: readonly ApplicationFieldInput[]; values: Readonly<Record<string, string>> }) { return <dl className="grid gap-x-6 gap-y-3 text-sm sm:grid-cols-2">{fields.filter((field) => field.enabled).map((field) => <div key={field.id} className="grid grid-cols-[84px_1fr] gap-3"><dt className="text-muted">{field.label}</dt><dd className="break-words font-medium">{reviewValue(field, values) || <span className="font-normal text-muted">미입력</span>}</dd></div>)}</dl>; }

function reviewValue(field: ApplicationFieldInput, values: Readonly<Record<string, string>>) { if (field.inputType === "COMPOSITE") return field.config.fields?.map((part) => `${values[`${field.id}.${part.key}`] || "-"}${part.unit ?? ""}`).join(" · "); return values[field.id]; }

function MediaSummary({ photos, videoUrl }: { photos: readonly ApplicationPhoto[]; videoUrl: string }) { const videoId = youtubeVideoId(videoUrl); return <div>{photos.length ? <div className="flex gap-2 overflow-x-auto pb-1">{photos.map((photo, index) => <div key={photo.id} className="relative h-[88px] w-[66px] shrink-0 overflow-hidden rounded-md border border-border"><Image src={photo.url} alt={index === 0 ? "대표 프로필 사진" : photo.name} fill unoptimized sizes="66px" className="object-cover" />{index === 0 ? <span className="absolute bottom-0 left-0 right-0 bg-brand px-1 py-0.5 text-center text-[10px] font-semibold text-white">대표</span> : null}</div>)}</div> : <p className="text-sm text-muted">사진 없음</p>}<p className="mt-3 text-sm text-muted-strong">{videoId ? `영상 · youtu.be/${videoId}` : "영상 미첨부"}</p></div>; }

function CareerSummary({ noCareer, careers }: { noCareer: boolean; careers: readonly CareerDraft[] }) { if (noCareer) return <p className="text-sm text-muted">경력 없음 (신인)</p>; if (!careers.length) return <p className="text-sm text-muted">미입력</p>; return <ul className="divide-y divide-border-soft">{careers.map((career) => <li key={career.id} className="flex gap-3 py-2 text-sm"><span className="num text-muted">{career.year}</span><span className="font-medium">{career.title}</span><span className="ml-auto text-muted">{career.part}</span></li>)}</ul>; }

function Consent({ consent, disabled, onChange }: { consent: boolean; disabled: boolean; onChange: (consent: boolean) => void }) { return <label className={`mt-7 flex items-start gap-3 border-y border-border py-5 ${disabled ? "cursor-not-allowed opacity-70" : "cursor-pointer"}`}><input type="checkbox" checked={consent} disabled={disabled} onChange={(event) => onChange(event.target.checked)} className="mt-1 h-4 w-4 shrink-0 accent-brand" /><span><strong className="block text-sm"><span className="mr-1 text-fail">[필수]</span>개인정보 수집·이용에 동의합니다</strong><span className="mt-1 block text-sm leading-6 text-muted">제출한 정보는 이번 공고 심사에만 사용하며, 전형 종료 후 6개월이 지나면 파기합니다.</span></span></label>; }

function SubmissionArea({ disabled, consent, state, error, onSubmit }: { disabled: boolean; consent: boolean; state: SubmissionState; error: string; onSubmit: (result: "SUCCESS" | "ERROR") => void }) { return <div className="mt-6"><p className="text-sm text-muted">제출 후에는 내용을 수정할 수 없어요.</p>{error ? <p role="alert" className="mt-3 rounded-control border border-fail/20 bg-fail-bg px-4 py-3 text-sm font-medium text-fail">{error}</p> : null}<button type="button" disabled={disabled || !consent} onClick={() => onSubmit("SUCCESS")} className="mt-4 inline-flex min-h-12 w-full items-center justify-center rounded-control bg-brand px-5 text-base font-semibold text-white transition-colors hover:bg-brand-strong disabled:bg-border disabled:text-muted">{state === "SUBMITTING" ? "제출 중…" : "지원서 제출"}</button><button type="button" disabled={disabled} onClick={() => onSubmit("ERROR")} className="mx-auto mt-3 block min-h-9 px-3 text-xs font-semibold text-muted hover:text-fail">목 실패 상태 확인</button></div>; }
