package art.yesulin.global.audit;

public enum AdminAction {

    MEMBER_STATUS_CHANGED,
    SUBMISSION_DELETED,
    FILE_DELETED,
    SHOW_HOST_NAME_CHANGED,
    SHOW_CREATED,
    SHOW_STATUS_CHANGED,
    SHOW_DELETED,
    TIMETABLE_MESSAGE_SENT,
    AUDITION_POST_IMPORTED,
    AUDITION_POST_STATUS_CHANGED
}
